services:
  - type: web
    name: vaultgate-auth
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node scripts/initDb.js && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: APP_NAME
        value: VaultGate
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM_NAME
        value: VaultGate
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: BREVO_API_KEY
        sync: false
